CL04biller/config/routes.rb
Rails.application.routes.draw do

  resources :accounts

end

CL04biller/app/models/account.rb
class Account < ActiveRecord::Base
	has_many :account_entries
end

CL04biller/app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
	belongs_to :account
end

CL04biller/app/models/customer.rb
class Customer < Account
	has_many :time_entries
	def total_hours
		time_entries.sum(:time)
	end
end

CL04biller/app/models/employee.rb
class Employee < Account
	has_many :time_entries
	has_and_belongs_to_many :projects, :join_table => "employees_projects"

	def total_hours
		time_entries.sum(:time)
	end
	def log_time(amount, customer)
		TimeEntry.create(time: amount, employee: self, account: customer)
	end
end

CL04biller/app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :employees, :join_table => "employees_projects"
end

CL04biller/app/models/time_entry.rb
class TimeEntry < AccountEntry
	belongs_to :customer
	belongs_to :employee
end

CL04biller/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :set_accounts
	def index
	end
	def show
		@account = Account.find(params[:id])
	end
	def new
		@account = Account.new
		@account.type = params[:type]
	end

	def set_accounts
		@accounts = Account.all
	end
end

CL04biller/app/helpers/accounts_helper.rb
module AccountsHelper
end

CL04biller/app/views/accounts/_customer_log.html.erb
Customer

CL04biller/app/views/accounts/_employee_log.html.erb
<%@accounts.each do |a|%>
<%	if a.type == "Customer"%>
	<h3><%=a.name%></h3>
<%		a.time_entries.each do |t|%>
<%			if t.employee.id == @account.id%>

<%			end%>
<%	end%>
<%end%>

CL04biller/app/views/accounts/index.html.erb
<div class="customer-accounts">
	<h1>Customers</h1>
<%@accounts.each do |a|%>
	<%if a.type == "Customer"%>
		<div class="account">
			<h2><%=link_to a.name,account_path(a)%></h2>
			<p><%=a.about%></p>
			<h4>Account Entries: (<%=a.account_entries.count%>)</h4>
		</div>
	<%end%>
<%end%>
<%= link_to "Register a new Customer", new_account_path(:type =>"Customer")%> 
</div>

<div class="employee-accounts">
	<h1>Employees</h1>
<%@accounts.each do |a|%>
	<%if a.type == "Employee"%>
		<div class="account">
			<h2><%=link_to a.name,account_path(a)%></h2>
			<h4>Account Entries: (<%=a.account_entries.count%>)</h4>
		</div>
	<%end%>
<%end%>
<%= link_to "Register a new Employee", new_account_path(:type =>"Employee")%> 
</div>

CL04biller/app/views/accounts/new.html.erb
<h1>New <%=@account.type%></h1>

<%= form_for(@account) do |a| %>
  <div class="field">
    <%= a.label :name %><br>
    <%= a.text_field :name %>
  </div>
  <div class="field">
    <%= a.label :email %><br>
    <%= a.text_field :email %>
  </div>
  <%if @account.type == "Customer"%>
  <div class="field">
    <%= a.label :about %><br>
    <%= a.text_area :about %>
  </div>
  <%end%>
  <div class="actions">
    <%= a.submit ("Create #{@account.type}")%>
  </div>
<% end %>

CL04biller/app/views/accounts/show.html.erb
<h1><%=@account.name%></h1>
<h4>Account Entries</h4>
<%if @account.type == "Customer" %>
<%=	render "customer_log"%>
<%end%>
<%if @account.type == "Employee"%>
<%=	render "employee_log"%>
<%end%>

<% @account.account_entries.each do |e| %>
	<p><%=e.inspect%></p>
<%end%>

CL04biller/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CL04biller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>